name: Docker Image CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make image DOCKER=docker
        if: contains(github.event.pull_request.labels.*.name, 'autodocker')

