name: Docker Image CI

on:
  push:
      branches:
          - auto/wine-updates
  pull_request:
      types:
          - labeled
          - synchronized

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make image DOCKER=docker
        if: contains(github.event.pull_request.labels.*.name, 'autodocker')

