name: Release

on:
    release:
        types: [published]

jobs:
  build:
    env:
        BASENAME: panard/mtgo
        TAG: latest
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image
        uses: actions-hub/docker@master
        with:
            args: pull $BASENAME:$GITHUB_REF
      - run: docker tag $BASENAME:$GITHUB_REF $BASENAME:$TAG
      - name: Push image
        uses: actions-hub/docker@master
        with:
            args: push $BASENAME:$TAG


